-- AlterTable
ALTER TABLE `Team` ADD COLUMN `manualDraws` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `manualLosses` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `manualPlayed` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `manualWins` INTEGER NOT NULL DEFAULT 0;
